### ISSUE TITLE
Implement AutoCloseable interface

### ISSUE THREAD

**Issue by lospejos** [vibur/vibur-object-pool#1]
Consider to implement the AutoCloseable interface to make pool able to be used in "try-with-resources" statements.

**Comment by simeonmalchev** [comment]
Implementing AutoCloseable is completely reasonable and not at all difficult to implement enhancement, however at the moment all Vibur projects produce Java 6 compatible artifacts, while AutoCloseable and the try-with-resources statement are Java 7 features. This means that the source/target parameters for javac in the pom.xml of all Vibur projects needs to change from 1.6 to 1.7, and the new Vibur artifacts produced this way will no longer be Java 6 compatible. I can possibly do this from the next major Vibur version 9.0, I'll think further about it. At this moment I cannot tell, however, when the next major Vibur version will be ready to get out.

**Comment by lospejos** [comment]
As an option, you could create two vibur-bject-pool versions or branches ("old" - for those who uses Java 6, and "new" - for those who uses AutoCloseable-aware Java versions, 7+).

**Comment by simeonmalchev** [comment]
Fixed on master, should be able to release to Maven Central in a week.

**Comment by simeonmalchev** [comment]
Release 9.0 is now available from Maven Central.
