### ISSUE TITLE
Expire objects in pool after a timeout

### ISSUE THREAD

**Issue by ado2000** [vibur/vibur-object-pool#9]
Hi, nice component, 

is there a way to auto remove the object from pool ?

For instance, after 5 seconds that the object is not used check for remove it from the pool and remove it.

Thanks

**Comment by simeonmalchev** [comment]
Hi @ado2000, sorry for my slow reply, this message got me between other things..

No, there is no direct way to remove/expire objects from the pool based on individual object age. In my experience, the total number of the objects in the pool is much more important than the individual age of each particular object in the pool. The pool has two methods: reduceCreatedBy(..) and reduceCreatedTo(..) that can help you to control the total number of objects in the pool. The pool has also an utility class SamplingPoolReducer that does automatic pool size control, however, bear in mind that this utility class will start one background service thread.

For an example of how SamplingPoolReducer is used see the sources of https://github.com/vibur/vibur-dbcp . If you need to know and control the objects in the pool by their individual age, then you need to keep in the pool stateful objects. Perhaps you can enrich your current objects with a long variable containing their nanoTime(). You can see at https://github.com/vibur/vibur-dbcp/blob/master/src/main/java/org/vibur/dbcp/pool/ConnectionFactory.java#L116 how I'm checking the age of the objects in the pool. ConnHolder is the stateful object in my case.

Again, I'm recommending you to control the total number of objects in the pool, and to go to individual objects age control only if necessary.

And of course, if you finish using the project, consider starring it on github.

**Comment by ado2000** [comment]
Hi Simeon,

Thanks for you response, it is so much appreciated, 

What I’m working on is a smtp connection pool used for a self made smtp server.

The correct way to work should be this one:

1) Open a connection to smtp server
2) Use the connection sto send messages
3) If no connection is available, open a new connection
4) Leave the connection open for a while waiting to reuse it.
5) If the connection is not used and the tile is expired, then close the connection.
6) If no connection are present into the pool then terminate the pool.

What I did for now is a thread like this that runs every 30 seconds and remove the connection not used.

Is this the correct way ?
May be I'll implement the time expiry as you did.

Thanks

`
	public void initPoolMaintenance() {
		
		threadPoolMaintenance = new Thread("New Thread - ") {
			public void run() {
				try {
		
					threadRunning = true;
					log.info("threadPoolMaintenance - Started.");
					
					while (true) {

						ConcurrentHashMap<PoolKey, PoolService<SmtpClient>> poolMap = SmtpClientPool
								.getSocketConnectionPoolsMap();

						poolMap.forEach((k, v) -> {
							
							log.debug("IP: " + k.getIp() + " Domain: " + k.getDomain() + " Pool size: " + v.createdTotal());

							v.reduceCreatedTo(0, true);
							
							if(v.taken() == 0 ) {
								v.terminate();
							}
							
						});
						
						poolMap.forEach((k, v) -> {
											
							if(v.isTerminated()) poolMap.remove(k);
							
						});
						
						
						if(threadRunning == false) break;
						
						Thread.sleep(30000);
					}
					
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				
				log.info("threadPoolMaintenance - Stopped.");
				
			}
		};

		threadPoolMaintenance.start();
				
	}
`

**Comment by simeonmalchev** [comment]
@ado2000 I think that you probably don't need to terminate the pool and then to remove it from the map. I.e., these two parts:
```
                if(v.taken() == 0 ) {
			v.terminate();
		}
```
and 
```
               poolMap.forEach((k, v) -> {					
			if(v.isTerminated()) poolMap.remove(k);
		});
```
are probably not needed.

An empty pool is a very thin object and doesn't consume memory. You may need to remove the pools from the map only if you are using a very large number of pools. Otherwise, the rest of the solution looks fine to me. I mean, if you need to traverse your pools in a service thread once in a 30 secs and close all currently idle connections in all pools, that's fine.

**Comment by ado2000** [comment]
Hi Simeon, 

thanks for the suggestion,

in my case, the number of pool could be very hight, ( tens of thousands ) may be I can clean the empty pool less frequently, may be each 5 minutes or something like that.

but the best solution for me is to remove the object from the pool after a specific amount of time ( 5 minutes ) and also remove the pool after a specific time ( 30 minutes ) 

May be i'll try to implement a time based expiration.

Thanks

**Comment by simeonmalchev** [comment]
If you have such a large number of pools it is fair to remove them from the cache periodically. Creation of a new pool is a cheap operations, so no problems with that. I have actually designed once a similar solution myself. The tweaking of the timeout values will be more or less a trial and error exercise. It is hard to say in advance what values will be best for that.

If you happy with the current discussion, please close the issue when you decide.

**Comment by ado2000** [comment]
Thanks for your help.

Regards.
